# Generated by Django 3.0.3 on 2020-06-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200621_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='C:\\Users\\DELL\\Downloads\\newspaper_project\\media'),
            preserve_default=False,
        ),
    ]
