# Generated by Django 3.0.3 on 2020-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200622_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoty',
            field=models.CharField(choices=[('SPORT', 'sport'), ('POLITICS', 'politics'), ('FILMS', 'films'), ('NEWS', 'news')], default=('NEWS', 'news'), max_length=100),
        ),
    ]
