# Generated by Django 3.0.3 on 2020-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200622_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\DELL\\Downloads\\newspaper_project\\media'),
        ),
    ]
