# Generated by Django 3.0.3 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200622_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='C:\\Users\\DELL\\Downloads\\newspaper_project\\media'),
            preserve_default=False,
        ),
    ]
